[kms/yubikey] Add decryption support to Yubikey KMS plugin
smallstep/crypto pull request #101
Opened 2022-10-18 15:58 UTC by fuhry

Some provisioners in `step-ca` (i.e. SCEP) require the ability to decrypt challenges using the intermediate CA key. [1] Although the Yubikey hardware supports decryption using RSA keys, support for this was missing from the Yubikey KMS plugin.

This commit implements the `CreateDecrypter` method in the Yubikey KMS plugin. Tests are included.

[1] https://github.com/smallstep/certificates/blob/361e2b2907bc94744da98ece290fdc1d851951f4/authority/authority.go#L540-L545

Signed-Off-By: Dan Fuhry <dan@fuhry.com>

#### Name of feature: Decrypter support for Yubikey KMS plugin

#### Pain or issue this feature alleviates: Inability to use SCEP provisioner when intermediate CA is stored on a Yubikey

2022-10-18 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/crypto?pullRequest=101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/crypto?pullRequest=101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/crypto?pullRequest=101) it.</sub>

2022-10-18 16:02 UTC, fuhry commented
TODO: the CreateSigner and CreateDecrypter methods could be DRYed out a bit

2022-10-19 00:09 UTC, maraino commented
Nice, I wanted to do this at some point.

2022-10-19 00:19 UTC, maraino requested changes

2022-10-19 00:19 UTC, maraino commented on kms/yubikey/yubikey.go
> +	}
Although `CreateSigner` is implemented this way, in other KMSs, to create a signer, you need to `CreateKey -> CreateSigner`. We should use the same logic for `CreateDecrypter`, `CreateKey -> CreateDecrypter`.

I'll add a PR to fix `CreateSigner`

2022-10-19 00:21 UTC, maraino commented on kms/yubikey/yubikey.go
> +	}
No, I though this method was generating the key, I'm wrong.

2022-10-19 01:33 UTC, merged

2022-10-20 22:41 UTC, fuhry commented
Thanks for merging this!

It turns out that this PR on its own is not enough. The `*pki.keyRSA` (cast to `crypto.Decrypter`) returned from this doesn't match the cases checked in [pkcs7/decrypt.go](https://github.com/smallstep/pkcs7/blob/5660c44b3d3b8a1c4a125dee9ecfd658efb3f437/decrypt.go#L34), so [here's a PR to fix that](https://github.com/smallstep/pkcs7/pull/3).