Split ReadCertificate functions into parsing files and bytes
smallstep/crypto pull request #546
Opened 2024-07-10 23:41 UTC by dopey

2024-07-10 23:46 UTC, maraino requested changes
We already have `ParseCertificate`, `ParseCertificateBundle`, and `ParseCertificateRequest` we don't need new methods that get bytes as the input.

2024-07-11 18:08 UTC, maraino requested changes

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +		return nil, errors.Wrapf(err, "error parsing %s", ctx.filename)
Return an InvalidPEMError

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +	ctx := newContext("certificate-request-bytes")
ditto

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +	ctx := newContext("certificate-bundle-bytes")
In fact, we're not writing files, so a context can be just 
```go
var ctx context
if err := ctx.apply(opts); err != nil {
	return nil, err
}
```

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
>  	}
ditto

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +	return csr, errors.Wrapf(err, "error parsing %s", ctx.filename)
ditto InvalidPEMError.

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +		WithAllowDER(),
```suggestion
```

2024-07-11 18:08 UTC, maraino commented on pemutil/pem.go
> +		WithAllowDER(),
```suggestion
```

2024-07-11 21:35 UTC, dopey commented on pemutil/pem.go
> +	ctx := newContext("certificate-bundle-bytes")
context needs to be a pointer, so I'd have to instantiate it with `var ctx = &context{}`. Feel like it's nicer to do just do `newContext()`.

2024-07-11 22:59 UTC, maraino requested changes

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +			}
[CertPool.AppendCertsFromPEM](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/crypto/x509/cert_pool.go;l=226-228) has the condition that you have removed:
```go
if block.Type != "CERTIFICATE" || len(block.Headers) != 0 {
	continue
}
```

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +				Message: fmt.Sprintf("error parsing %s: does not contain a valid PEM encoded certificate", filename),
You will get a similar error by default.
```suggestion
```

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +	}
I don't really like this.

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +			Message: fmt.Sprintf("error parsing %s as DER format: %v", filename, err),
I think the errors are more verbose than necessary. 

A better approach might be to return simpler errors in the `Parse*` methods and wrap them in the `Read*` methods with the filename:
```go
return fmt.Errorf("error parsing %s: %w", filename, err)
```

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +			Message: fmt.Sprintf("error parsing %s as DER format: %v", filename, err),
Bellow you're doing something different:
```go
return nil, &InvalidPEMError{
	File: ctx.filename,
	Type: PEMTypeCertificateRequest,
	Err:  err,
```

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +	)
We can get rid of the filename and options in the parse if we do:

```
certs, err := ParseCertificateBundle(b)
if err != nil {
	return fmt.Errorf("error parsing %s: %w", filename, err)
}
```

2024-07-11 22:59 UTC, maraino commented on pemutil/pem.go
> +	)
Ditto

2024-07-12 00:45 UTC, maraino requested changes

2024-07-12 00:45 UTC, maraino commented on pemutil/pem.go
> +			Message: fmt.Sprint("error parsing certificate request as DER format", err),
```suggestion
			Message: fmt.Sprint("error parsing certificate request as DER format: %v", err),
```

2024-07-12 01:02 UTC, maraino approved these changes

2024-07-12 02:35 UTC, merged